#!/usr/bin/env python3
"""port/assets/texture-policy.json as a C table (port/runtime/texture_policy.h), the way tools/embed_assets.py
embeds the HUD layout: the policy changes only with an app build, and the player cannot edit it.

  embed_texture_policy.py POLICY_JSON OUTPUT_C"""

import json
import sys
from pathlib import Path

RESULTS = {"s4g": "TEXTURE_POLICY_S4G", "bpf": "TEXTURE_POLICY_BPF", "original": "TEXTURE_POLICY_ORIGINAL"}


def string(text: str) -> str:
    if not text.isascii():
        raise SystemExit(f"embed_texture_policy: {text!r} is not ASCII")
    return json.dumps(text)          # a valid C string literal for ASCII: \\ and \" escaped


def array(name: str, values: list[str], lines: list[str]) -> str:
    if not values:
        return "NULL, 0"
    lines.append(f"static const char *const {name}[] = {{ {', '.join(string(v) for v in values)} }};")
    return f"{name}, {len(values)}"


def main() -> None:
    source, output = Path(sys.argv[1]), Path(sys.argv[2])
    raw = json.loads(source.read_text())
    if raw.get("schema") != 1:
        raise SystemExit(f"embed_texture_policy: {source}: schema {raw.get('schema')} is not 1")
    lines = [f"/* generated by tools/embed_texture_policy.py from {source.name}; do not edit */",
             '#include "texture_policy.h"', ""]
    names = array("graphic_names", raw["graphic_names"], lines)
    groups = array("graphic_groups", raw["graphic_groups"], lines)
    prefixes = array("decal_surface_prefixes", raw["decal_surface_prefixes"], lines)
    if raw["overrides"]:
        lines.append("static const struct texture_policy_override overrides[] = {")
        for o in raw["overrides"]:
            digest = string(o["hash"]) if "hash" in o else "NULL"
            lines.append(f"\t{{ {string(o['tag'])}, {o.get('index', -1)}, {digest}, {RESULTS[o['result']]} }},")
        lines.append("};")
        overrides = f"overrides, {len(raw['overrides'])}"
    else:
        overrides = "NULL, 0"
    r, f = raw["results"], raw["fallback"]
    lines += ["", "const struct texture_policy_table texture_policy_embedded = {",
              f"\t{raw['schema']}, {raw['policy_version']},",
              f"\t{RESULTS[r['graphic']]}, {RESULTS[r['surface']]}, {RESULTS[r['companion']]}, {RESULTS[r['bump']]},",
              f"\t{float(f['low'])}f, {float(f['high'])}f, {float(f['sigma'])}f, {int(f['iterations'])},",
              f"\t{names}, {groups}, {prefixes},", f"\t{overrides} }};", ""]
    text = "\n".join(lines)
    if not output.is_file() or output.read_text() != text:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(text)


if __name__ == "__main__":
    main()
